### ISSUE TITLE
Adding users to CentOS 8 fails due to installation of "libselinux-python" package

### ISSUE THREAD

**Issue by Jukepoika** [CSCfi/ansible-role-users#53]
Centos 8 uses 'python3-libselinux' instead of 'libselinux-python'.

Problematic task: 
![image](https://user-images.githubusercontent.com/55080591/93080155-ea51a280-f695-11ea-9a02-4327e96bcdaa.png)

Suggested fix:
![image](https://user-images.githubusercontent.com/55080591/93080238-0b19f800-f696-11ea-9a2f-cd94f5652bd3.png)

**Comment by Jukepoika** [comment]
@junousi Please check this out.

**Comment by junousi** [comment]
`>=` feels a bit unnecessary (and not implied by the play name). But in any case looks good, PR away! :)
